### ISSUE TITLE
yii2 depends on php5.4.*, this ext depends on php5.5.*

### ISSUE THREAD

**Issue by tomjamescn** [cedx/mustache.yii#2]
Is it possible change it to depends on php5.4.*?

**Comment by cedx** [comment]
I don't think so. The package already depends on PHPUnit 5 that requires PHP 5.6 or upper.
But the code seems to be fully compatible with PHP 5.4, so you can still use it.

I suggest you to use the [`platform`](https://getcomposer.org/doc/06-config.md#platform) field of the ` config` section in your `composer.json` file: it let you fake the version of the installed PHP runtime.

I already use this hack to let PHPUnit install properly on PHP 5.5 systems. See [my own `composer.json`](https://github.com/cedx/mustache.yii/blob/master/composer.json) file.

**Comment by tomjamescn** [comment]
Ok，I got it. Thank you~
